### ISSUE TITLE
DB設定ファイルにOS依存の内容が記載されている

### ISSUE THREAD

**Issue by seiya-takano** [WitStudy/PMSystem#20]
#1 にて挙がった課題ですが関連Issueとして再度掲示します。

当システム動作OSを任意としていますが
DB設定ファイル database.yml.example のソケット初期設定記述がCentOSのものとなっています。

```
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
```
CentOS以外の利用者に設定を変更する旨を記述する。
もしくは、CentOSを推奨OSとしてしまう等の対応が必要かと思われます。

ご検討、よろしくお願い致します。
